"""Base repository interface (sketch)."""
from __future__ import annotations
from typing import Protocol, Iterable, Generic, TypeVar

T = TypeVar("T")

class Repository(Protocol, Generic[T]):
    def add(self, obj: T) -> T: ...
    def get(self, obj_id: int) -> T | None: ...
    def list(self) -> Iterable[T]: ...
    def remove(self, obj_id: int) -> None: ...
